### ISSUE TITLE
Door won't open

### ISSUE THREAD

**Issue by yairchu** [incoherentsoftware/defect-process#1]
Hi! Very nice game!
Don't know if this is the appropriate place for bug reports,
but at one game at a "hit bouncing ball" level,
I couldn't progress from there:

<img width="1440" alt="Screen Shot 2021-10-10 at 13 05 44" src="https://user-images.githubusercontent.com/97606/136691248-6f6547b5-c215-4b83-8c71-a43d96f11c8d.png">

This is with version from Steam, on macOS 11.5.2 on M1 MBP

**Comment by incoherentsoftware** [comment]
Hi thanks for the bug report, and glad you're enjoying the game!  This looks like a floating point issue, fixed it as part of a change to add a small delay before the room exit barriers disappear. Just updated all versions of the steam build, restart the client if it isn't showing up in Downloads.

The relevant diff: https://gist.github.com/incoherentsoftware/5385315b2b8a7c5573f6bbf97133debd
Will followup and update this repository for the larger v0.8.2 changes.
