### ISSUE TITLE
Might be a great addition to nixos

### ISSUE THREAD

**Issue by nixinator** [incoherentsoftware/defect-process#2]
I'd be up for packaging this for nixos.

would you accept a flake.nix into the root of your repo?

Would you consider giving nixos users a limited game experience, perhaps a single level for running on this via nixos?

**Comment by incoherentsoftware** [comment]
> I'd be up for packaging this for nixos.
> 
> would you accept a flake.nix into the root of your repo?

Hi, thanks for the offer - am limiting official support to windows/linux/mac but I can link to an unofficial fork for nixOS from the readme, let me know.
 
> Would you consider giving nixos users a limited game experience, perhaps a single level for running on this via nixos?

Hmm I'd need to look into the nix package licensing situation, and whether I have legal permission (e.g. music licenses) for parts of the commercial data to include.  This isn't planned for now.
