### ISSUE TITLE
Won't build on Ubuntu 21.10

### ISSUE THREAD

**Issue by thalerjonathan** [incoherentsoftware/defect-process#4]
I have cloned the repo and am following the instructions under linux-setup.md, omitting Enable Game Audio. I have succesfully installed all SDL libraries by ``sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev``. However, when buildling with stack (Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4) I get the follwowing output:

```
> stack build --local-bin-path . --copy-bins
sdl2          > configure
sdl2          > Configuring sdl2-2.5.3.0...
sdl2          > Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7: The pkg-config package 'sdl2'
sdl2          > version ==2.0.6 || >2.0.6 is required but it could not be found.
sdl2          > 
```

**Comment by incoherentsoftware** [comment]
Hmm the error message suggests it can't find SDL2 (the library itself not the bindings) installed on your system, would recommend:
- verify that the `libSDL2*` files in https://packages.ubuntu.com/impish/amd64/libsdl2-dev/filelist exist on the local filesystem
- check that `PKG_CONFIG_PATH` is set https://stackoverflow.com/a/28218449

Can also try building and running the examples in https://github.com/haskell-game/sdl2 with cabal as a sanity check.

**Comment by thalerjonathan** [comment]
Thanks! The error was a missing ``PKG_CONFIG_PATH`` https://stackoverflow.com/a/28218449, which needed to be set to ``/lib/x86_64-linux-gnu/pkgconfig`` in my case. It compiles fine now.
