### ISSUE TITLE
FMOD libs require setting LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by thalerjonathan** [incoherentsoftware/defect-process#5]
I managed to build the game including Game Audio by following the steps in `linux-setup.md`. However, when trying to start the game with `./defect-process` I get the error `./defect-process: error while loading shared libraries: libfmod.so.13: cannot open shared object file: No such file or directory`. 

When setting the `LD_LIBRARY_PATH` to `<project root>/lib` it works. Not sure if it is an issue with my system (Ubuntu 21.10) but maybe it helps to add this info to `linux-setup.md`.

**Comment by incoherentsoftware** [comment]
Hmm you're right the instructions should specify setting the library path.  Just updated with https://github.com/incoherentsoftware/defect-process/commit/da7fe666b89d6566939b6bc272b1eb93d76ebe38, thanks!
