### ISSUE TITLE
Input not detected when compiled with SDL 2.0.20

### ISSUE THREAD

**Issue by incoherentsoftware** [incoherentsoftware/defect-process#6]
Compiling with SDL 2.0.20 has problems with input detection (e.g. mouse clicks/keyboard presses not registering) due to an open upstream issue (https://github.com/haskell-game/sdl2/issues/245).  Will need to use an earlier SDL version between [2.0.10, 2.0.18] for now, the Steam build is using 2.0.10.

Have reproduced the issue on Arch Linux and Ubuntu so far, this may also affect Windows and macOS.

**Comment by dpwiz** [comment]
I merged some polling [fix](https://github.com/haskell-game/sdl2/pull/242), please try with sdl2 master.

**Comment by incoherentsoftware** [comment]
> I merged some polling [fix](https://github.com/haskell-game/sdl2/pull/242), please try with sdl2 master.

Thanks, in initial testing input detection appears to be working on Linux again using the latest bindings (https://github.com/haskell-game/sdl2/commit/432f666cf39c6d28037600d465971eb1124f7897) with SDL 2.0.20.  Will continue testing, but seems good so far.

**Comment by incoherentsoftware** [comment]
Fixed in 688680814b0189bf0b792cd99e0d1bd0f7f2f9d9
